const providerLanguages = [
  "ar",
  "bg",
  "cs",
  "da",
  "de",
  "el",
  "en",
  "es",
  "et",
  "fi",
  "fr",
  "he",
  "hi",
  "hu",
  "id",
  "it",
  "ja",
  "ko",
  "lt",
  "lv",
  "ms",
  "nl",
  "no",
  "pl",
  "pt",
  "ro",
  "ru",
  "sk",
  "sv",
  "th",
  "tr",
  "uk",
  "vi",
  "zh",
] as const;

type ProviderLanguage = (typeof providerLanguages)[number];
type ProviderKind = "json" | "webhook";

type ProviderCatalogRecord = {
  id: string;
  label: string;
  defaultCategory: string;
  language: ProviderLanguage;
  kind: ProviderKind;
};

const jsonProviderCatalog = [
  {
    id: "france-travail",
    label: "France Travail (ex Pôle emploi)",
    defaultCategory: "engineering",
    language: "fr",
    kind: "json",
  },
  {
    id: "apec",
    label: "APEC",
    defaultCategory: "operations",
    language: "fr",
    kind: "json",
  },
  {
    id: "meteojob",
    label: "Meteojob",
    defaultCategory: "marketing",
    language: "fr",
    kind: "json",
  },
  {
    id: "hellowork",
    label: "HelloWork / RegionsJob",
    defaultCategory: "engineering",
    language: "fr",
    kind: "json",
  },
  {
    id: "welcometothejungle",
    label: "Welcome to the Jungle",
    defaultCategory: "product",
    language: "fr",
    kind: "json",
  },
  {
    id: "jobteaser",
    label: "JobTeaser",
    defaultCategory: "marketing",
    language: "fr",
    kind: "json",
  },
  {
    id: "chooseyourboss",
    label: "ChooseYourBoss",
    defaultCategory: "engineering",
    language: "fr",
    kind: "json",
  },
  {
    id: "monster-fr",
    label: "Monster France",
    defaultCategory: "operations",
    language: "fr",
    kind: "json",
  },
  {
    id: "indeed-fr",
    label: "Indeed France",
    defaultCategory: "marketing",
    language: "fr",
    kind: "json",
  },
  {
    id: "talent-io",
    label: "talent.io",
    defaultCategory: "engineering",
    language: "fr",
    kind: "json",
  },
  {
    id: "arbeitnow",
    label: "Arbeitnow",
    defaultCategory: "engineering",
    language: "de",
    kind: "json",
  },
  {
    id: "jobicy",
    label: "Jobicy",
    defaultCategory: "operations",
    language: "en",
    kind: "json",
  },
  {
    id: "remoteok",
    label: "RemoteOK",
    defaultCategory: "engineering",
    language: "en",
    kind: "json",
  },
  {
    id: "thehub",
    label: "The Hub",
    defaultCategory: "product",
    language: "en",
    kind: "json",
  },
  {
    id: "weworkremotely",
    label: "We Work Remotely (RSS)",
    defaultCategory: "engineering",
    language: "en",
    kind: "json",
  },
  {
    id: "hackernews-jobs",
    label: "Hacker News Jobs",
    defaultCategory: "engineering",
    language: "en",
    kind: "json",
  },
  {
    id: "headhunter",
    label: "HeadHunter",
    defaultCategory: "operations",
    language: "ru",
    kind: "json",
  },
  {
    id: "torre",
    label: "Torre",
    defaultCategory: "product",
    language: "es",
    kind: "json",
  },
  {
    id: "zippia",
    label: "Zippia",
    defaultCategory: "engineering",
    language: "en",
    kind: "json",
  },
  {
    id: "themuse",
    label: "The Muse",
    defaultCategory: "operations",
    language: "en",
    kind: "json",
  },
] as const satisfies readonly ProviderCatalogRecord[];

const webhookProviderCatalog = [
  // Indeed network
  { id: "indeed-us", label: "Indeed (US)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "indeed-uk", label: "Indeed (UK)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "indeed-de", label: "Indeed (DE)", defaultCategory: "engineering", language: "de", kind: "webhook" },
  { id: "indeed-es", label: "Indeed (ES)", defaultCategory: "engineering", language: "es", kind: "webhook" },
  { id: "indeed-it", label: "Indeed (IT)", defaultCategory: "engineering", language: "it", kind: "webhook" },
  { id: "indeed-nl", label: "Indeed (NL)", defaultCategory: "engineering", language: "nl", kind: "webhook" },
  { id: "indeed-ca", label: "Indeed (CA)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "indeed-br", label: "Indeed (BR)", defaultCategory: "engineering", language: "pt", kind: "webhook" },
  { id: "indeed-mx", label: "Indeed (MX)", defaultCategory: "engineering", language: "es", kind: "webhook" },
  { id: "indeed-ie", label: "Indeed (IE)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "indeed-au", label: "Indeed (AU)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "indeed-nz", label: "Indeed (NZ)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "indeed-in", label: "Indeed (IN)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "indeed-sg", label: "Indeed (SG)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "indeed-jp", label: "Indeed (JP)", defaultCategory: "engineering", language: "ja", kind: "webhook" },
  // Glassdoor
  { id: "glassdoor-fr", label: "Glassdoor (FR)", defaultCategory: "product", language: "fr", kind: "webhook" },
  { id: "glassdoor-uk", label: "Glassdoor (UK)", defaultCategory: "product", language: "en", kind: "webhook" },
  { id: "glassdoor-de", label: "Glassdoor (DE)", defaultCategory: "product", language: "de", kind: "webhook" },
  { id: "glassdoor-us", label: "Glassdoor (US)", defaultCategory: "product", language: "en", kind: "webhook" },
  { id: "glassdoor-ca", label: "Glassdoor (CA)", defaultCategory: "product", language: "en", kind: "webhook" },
  { id: "glassdoor-in", label: "Glassdoor (IN)", defaultCategory: "product", language: "en", kind: "webhook" },
  { id: "glassdoor-au", label: "Glassdoor (AU)", defaultCategory: "product", language: "en", kind: "webhook" },
  // LinkedIn
  { id: "linkedin-fr", label: "LinkedIn (FR)", defaultCategory: "engineering", language: "fr", kind: "webhook" },
  { id: "linkedin-de", label: "LinkedIn (DE)", defaultCategory: "engineering", language: "de", kind: "webhook" },
  { id: "linkedin-es", label: "LinkedIn (ES)", defaultCategory: "engineering", language: "es", kind: "webhook" },
  { id: "linkedin-uk", label: "LinkedIn (UK)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "linkedin-it", label: "LinkedIn (IT)", defaultCategory: "engineering", language: "it", kind: "webhook" },
  { id: "linkedin-us", label: "LinkedIn (US)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "linkedin-ca", label: "LinkedIn (CA)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "linkedin-br", label: "LinkedIn (BR)", defaultCategory: "engineering", language: "pt", kind: "webhook" },
  { id: "linkedin-in", label: "LinkedIn (IN)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "linkedin-au", label: "LinkedIn (AU)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "linkedin-sg", label: "LinkedIn (SG)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "linkedin-hk", label: "LinkedIn (HK)", defaultCategory: "engineering", language: "zh", kind: "webhook" },
  // StepStone + Monster
  { id: "stepstone-de", label: "StepStone (DE)", defaultCategory: "operations", language: "de", kind: "webhook" },
  { id: "stepstone-nl", label: "StepStone (NL)", defaultCategory: "operations", language: "nl", kind: "webhook" },
  { id: "stepstone-be", label: "StepStone (BE)", defaultCategory: "operations", language: "fr", kind: "webhook" },
  { id: "stepstone-at", label: "StepStone (AT)", defaultCategory: "operations", language: "de", kind: "webhook" },
  { id: "stepstone-ch", label: "StepStone (CH)", defaultCategory: "operations", language: "de", kind: "webhook" },
  { id: "stepstone-pl", label: "StepStone (PL)", defaultCategory: "operations", language: "pl", kind: "webhook" },
  { id: "stepstone-fr", label: "StepStone (FR)", defaultCategory: "operations", language: "fr", kind: "webhook" },
  { id: "monster-us", label: "Monster (US)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "monster-uk", label: "Monster (UK)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "monster-de", label: "Monster (DE)", defaultCategory: "operations", language: "de", kind: "webhook" },
  { id: "monster-in", label: "Monster (IN)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "monster-ca", label: "Monster (CA)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "monster-ie", label: "Monster (IE)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "monster-au", label: "Monster (AU)", defaultCategory: "operations", language: "en", kind: "webhook" },
  // UK & IE
  { id: "reed-uk", label: "Reed.co.uk", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "totaljobs-uk", label: "TotalJobs (UK)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "jobserve-uk", label: "JobServe (UK)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "irishjobs-ie", label: "IrishJobs", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "cvlibrary-uk", label: "CV-Library (UK)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "jobs-ie", label: "Jobs.ie", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "hackajob-uk", label: "hackajob (UK)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "cord-uk", label: "cord (UK)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "otta-uk", label: "Otta (UK)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  // DACH & Benelux
  { id: "jobs-ch", label: "jobs.ch", defaultCategory: "engineering", language: "de", kind: "webhook" },
  { id: "jobup-ch", label: "Jobup.ch", defaultCategory: "operations", language: "fr", kind: "webhook" },
  { id: "honeypot-de", label: "Honeypot (DE)", defaultCategory: "engineering", language: "de", kind: "webhook" },
  { id: "wearedevelopers-de", label: "WeAreDevelopers (DE)", defaultCategory: "engineering", language: "de", kind: "webhook" },
  { id: "wearedevelopers-at", label: "WeAreDevelopers (AT)", defaultCategory: "engineering", language: "de", kind: "webhook" },
  { id: "techtopjobs-be", label: "TechTopJobs (BE)", defaultCategory: "engineering", language: "fr", kind: "webhook" },
  { id: "ictjob-be", label: "ictjob (BE)", defaultCategory: "engineering", language: "fr", kind: "webhook" },
  { id: "jobware-de", label: "Jobware (DE)", defaultCategory: "operations", language: "de", kind: "webhook" },
  { id: "stellenanzeigen-de", label: "Stellenanzeigen (DE)", defaultCategory: "operations", language: "de", kind: "webhook" },
  { id: "kimeta-de", label: "Kimeta (DE)", defaultCategory: "operations", language: "de", kind: "webhook" },
  { id: "jobindex-dk", label: "Jobindex (DK)", defaultCategory: "operations", language: "da", kind: "webhook" },
  { id: "jobbsafari-se", label: "Jobbsafari (SE)", defaultCategory: "operations", language: "sv", kind: "webhook" },
  { id: "platsbanken-se", label: "Platsbanken (SE)", defaultCategory: "operations", language: "sv", kind: "webhook" },
  { id: "jobbnorge-no", label: "JobbNorge (NO)", defaultCategory: "operations", language: "no", kind: "webhook" },
  { id: "finn-no", label: "FINN Jobs (NO)", defaultCategory: "operations", language: "no", kind: "webhook" },
  { id: "arbeidsplassen-no", label: "Arbeidsplassen (NO)", defaultCategory: "operations", language: "no", kind: "webhook" },
  { id: "duunitori-fi", label: "Duunitori (FI)", defaultCategory: "operations", language: "fi", kind: "webhook" },
  { id: "oikotie-fi", label: "Oikotie (FI)", defaultCategory: "operations", language: "fi", kind: "webhook" },
  { id: "jobsfinland-fi", label: "Jobs in Finland", defaultCategory: "operations", language: "fi", kind: "webhook" },
  { id: "cvonline-lv", label: "CV-Online (LV)", defaultCategory: "operations", language: "lv", kind: "webhook" },
  { id: "cvonline-ee", label: "CV-Online (EE)", defaultCategory: "operations", language: "et", kind: "webhook" },
  { id: "cvonline-lt", label: "CV-Online (LT)", defaultCategory: "operations", language: "lt", kind: "webhook" },
  // Southern Europe
  { id: "infojobs-es", label: "InfoJobs (ES)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "infojobs-it", label: "InfoJobs (IT)", defaultCategory: "operations", language: "it", kind: "webhook" },
  { id: "tecnoempleo-es", label: "Tecnoempleo (ES)", defaultCategory: "engineering", language: "es", kind: "webhook" },
  { id: "infoempleo-es", label: "InfoEmpleo (ES)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "landingjobs-eu", label: "Landing.Jobs (EU)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "relocate-me", label: "Relocate.me", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "jobbatical", label: "Jobbatical", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "angelmatch-global", label: "AngelMatch", defaultCategory: "product", language: "en", kind: "webhook" },
  // Eastern Europe
  { id: "pracuj-pl", label: "Pracuj.pl", defaultCategory: "operations", language: "pl", kind: "webhook" },
  { id: "praca-sk", label: "Praca.sk", defaultCategory: "operations", language: "sk", kind: "webhook" },
  { id: "nofluffjobs-pl", label: "No Fluff Jobs (PL)", defaultCategory: "engineering", language: "pl", kind: "webhook" },
  { id: "nofluffjobs-cz", label: "No Fluff Jobs (CZ)", defaultCategory: "engineering", language: "cs", kind: "webhook" },
  { id: "nofluffjobs-hu", label: "No Fluff Jobs (HU)", defaultCategory: "engineering", language: "hu", kind: "webhook" },
  { id: "jobs-cz", label: "Jobs.cz", defaultCategory: "operations", language: "cs", kind: "webhook" },
  { id: "prace-cz", label: "Prace.cz", defaultCategory: "operations", language: "cs", kind: "webhook" },
  { id: "startupjobs-cz", label: "StartupJobs (CZ)", defaultCategory: "engineering", language: "cs", kind: "webhook" },
  { id: "jobsbg-bg", label: "Jobs.bg", defaultCategory: "operations", language: "bg", kind: "webhook" },
  { id: "ejobs-ro", label: "eJobs (RO)", defaultCategory: "operations", language: "ro", kind: "webhook" },
  { id: "bestjobs-ro", label: "BestJobs (RO)", defaultCategory: "operations", language: "ro", kind: "webhook" },
  { id: "profession-ua", label: "Profession (UA)", defaultCategory: "operations", language: "uk", kind: "webhook" },
  { id: "robota-ua", label: "Robota.ua", defaultCategory: "operations", language: "uk", kind: "webhook" },
  { id: "workua-ua", label: "Work.ua", defaultCategory: "operations", language: "uk", kind: "webhook" },
  { id: "superjob-ru", label: "SuperJob (RU)", defaultCategory: "operations", language: "ru", kind: "webhook" },
  { id: "rabota-by", label: "Rabota.by", defaultCategory: "operations", language: "ru", kind: "webhook" },
  // Remote & tech platforms
  { id: "stackshare-us", label: "StackShare (US)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "dice-us", label: "Dice (US)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "ziprecruiter-us", label: "ZipRecruiter (US)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "careerbuilder-us", label: "CareerBuilder (US)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "ladders-us", label: "The Ladders (US)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "flexjobs-global", label: "FlexJobs (Global)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "remotive-global", label: "Remotive (Global)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "powertofly-global", label: "PowerToFly (Global)", defaultCategory: "product", language: "en", kind: "webhook" },
  { id: "justremote-global", label: "JustRemote (Global)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "remote-co", label: "Remote.co", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "skip-the-drive", label: "SkipTheDrive", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "workingnomads-global", label: "Working Nomads", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "jobspresso-global", label: "Jobspresso", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "arc-dev", label: "Arc.dev", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "remoteeurope", label: "Remote Europe", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "jobspresso-global", label: "Jobspresso", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "wellfound-us", label: "Wellfound (US)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "angellist-eu", label: "AngelList (EU)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "angellist-in", label: "AngelList (IN)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "producthunt-jobs", label: "Product Hunt Jobs", defaultCategory: "product", language: "en", kind: "webhook" },
  { id: "dribbble-jobs", label: "Dribbble Jobs", defaultCategory: "design", language: "en", kind: "webhook" },
  { id: "behance-jobs", label: "Behance Jobs", defaultCategory: "design", language: "en", kind: "webhook" },
  { id: "workingnotworking", label: "Working Not Working", defaultCategory: "design", language: "en", kind: "webhook" },
  { id: "designjobsboard-uk", label: "Design Jobs Board (UK)", defaultCategory: "design", language: "en", kind: "webhook" },
  { id: "yc-jobs", label: "YC Jobs", defaultCategory: "engineering", language: "en", kind: "webhook" },
  // Asia Pacific
  { id: "seek-au", label: "SEEK (AU)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "seek-nz", label: "SEEK (NZ)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "jobstreet-sg", label: "JobStreet (SG)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "jobstreet-my", label: "JobStreet (MY)", defaultCategory: "engineering", language: "ms", kind: "webhook" },
  { id: "jobstreet-ph", label: "JobStreet (PH)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "jobstreet-id", label: "JobStreet (ID)", defaultCategory: "engineering", language: "id", kind: "webhook" },
  { id: "jobstreet-vn", label: "JobStreet (VN)", defaultCategory: "engineering", language: "vi", kind: "webhook" },
  { id: "jobsdb-hk", label: "JobsDB (HK)", defaultCategory: "operations", language: "zh", kind: "webhook" },
  { id: "jobsdb-th", label: "JobsDB (TH)", defaultCategory: "operations", language: "th", kind: "webhook" },
  { id: "jobsdb-sg", label: "JobsDB (SG)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "jobsdb-id", label: "JobsDB (ID)", defaultCategory: "operations", language: "id", kind: "webhook" },
  { id: "cpjobs-hk", label: "CPJobs (HK)", defaultCategory: "operations", language: "zh", kind: "webhook" },
  { id: "jobthai-th", label: "JobThai (TH)", defaultCategory: "operations", language: "th", kind: "webhook" },
  { id: "jobscentral-sg", label: "JobsCentral (SG)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "mycareersfuture-sg", label: "MyCareersFuture (SG)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "jobkorea-kr", label: "JobKorea", defaultCategory: "operations", language: "ko", kind: "webhook" },
  { id: "saramin-kr", label: "Saramin", defaultCategory: "operations", language: "ko", kind: "webhook" },
  { id: "wanted-kr", label: "Wanted (KR)", defaultCategory: "engineering", language: "ko", kind: "webhook" },
  { id: "wantedly-jp", label: "Wantedly (JP)", defaultCategory: "engineering", language: "ja", kind: "webhook" },
  { id: "wantedly-sg", label: "Wantedly (SG)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "green-japan", label: "Green (JP)", defaultCategory: "engineering", language: "ja", kind: "webhook" },
  { id: "mynavi-jp", label: "Mynavi (JP)", defaultCategory: "operations", language: "ja", kind: "webhook" },
  { id: "rikunabi-jp", label: "Rikunabi (JP)", defaultCategory: "operations", language: "ja", kind: "webhook" },
  // India & South Asia
  { id: "naukri-in", label: "Naukri (IN)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "shine-in", label: "Shine (IN)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "foundit-in", label: "Foundit (IN)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "instahyre-in", label: "Instahyre (IN)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "hirist-in", label: "Hirist (IN)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "cutshort-in", label: "Cutshort (IN)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "jobsforher-in", label: "JobsForHer (IN)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "techgig-in", label: "TechGig (IN)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  // Middle East
  { id: "bayt-gcc", label: "Bayt (GCC)", defaultCategory: "operations", language: "ar", kind: "webhook" },
  { id: "gulftalent-uae", label: "GulfTalent (UAE)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "akhtaboot-jo", label: "Akhtaboot (JO)", defaultCategory: "operations", language: "ar", kind: "webhook" },
  { id: "wadhefa-sa", label: "Wadhefa (SA)", defaultCategory: "operations", language: "ar", kind: "webhook" },
  { id: "naukrigulf-uae", label: "NaukriGulf (UAE)", defaultCategory: "operations", language: "en", kind: "webhook" },
  // Africa
  { id: "jobberman-ng", label: "Jobberman (NG)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "jobberman-gh", label: "Jobberman (GH)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "brightermonday-ke", label: "BrighterMonday (KE)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "brightermonday-ug", label: "BrighterMonday (UG)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "pnet-za", label: "PNet (ZA)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "careers24-za", label: "Careers24 (ZA)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "jobmail-za", label: "Job Mail (ZA)", defaultCategory: "operations", language: "en", kind: "webhook" },
  // Latin America
  { id: "catho-br", label: "Catho (BR)", defaultCategory: "operations", language: "pt", kind: "webhook" },
  { id: "gupy-br", label: "Gupy (BR)", defaultCategory: "operations", language: "pt", kind: "webhook" },
  { id: "bumeran-ar", label: "Bumeran (AR)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "bumeran-pe", label: "Bumeran (PE)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "zonajobs-ar", label: "ZonaJobs (AR)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "zonajobs-mx", label: "ZonaJobs (MX)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "trabajando-cl", label: "Trabajando (CL)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "occ-mx", label: "OCCMundial (MX)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "computrabajo-mx", label: "Computrabajo (MX)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "computrabajo-co", label: "Computrabajo (CO)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "computrabajo-pe", label: "Computrabajo (PE)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "computrabajo-ar", label: "Computrabajo (AR)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "elempleo-co", label: "Elempleo (CO)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "elempleo-ec", label: "Elempleo (EC)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "elempleo-pa", label: "Elempleo (PA)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "multitrabajos-ec", label: "Multitrabajos (EC)", defaultCategory: "operations", language: "es", kind: "webhook" },
  { id: "workana-latam", label: "Workana LATAM", defaultCategory: "product", language: "es", kind: "webhook" },
  { id: "tecnoempleo-es", label: "Tecnoempleo (ES)", defaultCategory: "engineering", language: "es", kind: "webhook" },
  { id: "getonbrd-cl", label: "GetOnBoard (CL)", defaultCategory: "engineering", language: "es", kind: "webhook" },
  { id: "getonbrd-pe", label: "GetOnBoard (PE)", defaultCategory: "engineering", language: "es", kind: "webhook" },
  { id: "hireline-mx", label: "Hireline (MX)", defaultCategory: "engineering", language: "es", kind: "webhook" },
  // Multinational aggregators
  { id: "eures-eu", label: "EURES Europe", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "adzuna-uk", label: "Adzuna (UK)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "adzuna-fr", label: "Adzuna (FR)", defaultCategory: "engineering", language: "fr", kind: "webhook" },
  { id: "adzuna-au", label: "Adzuna (AU)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "adzuna-ca", label: "Adzuna (CA)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "adzuna-us", label: "Adzuna (US)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "adzuna-nz", label: "Adzuna (NZ)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "adzuna-br", label: "Adzuna (BR)", defaultCategory: "engineering", language: "pt", kind: "webhook" },
  { id: "adzuna-mx", label: "Adzuna (MX)", defaultCategory: "engineering", language: "es", kind: "webhook" },
  { id: "adzuna-in", label: "Adzuna (IN)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  { id: "adzuna-sg", label: "Adzuna (SG)", defaultCategory: "engineering", language: "en", kind: "webhook" },
  // Hospitality & niche
  { id: "hosco-eu", label: "Hosco (EU)", defaultCategory: "operations", language: "en", kind: "webhook" },
  { id: "coolworks-us", label: "CoolWorks (US)", defaultCategory: "operations", language: "en", kind: "webhook" },
] as const satisfies readonly ProviderCatalogRecord[];

export const providerCatalog = [...jsonProviderCatalog, ...webhookProviderCatalog] as const;

if (process.env.NODE_ENV !== "production") {
  providerCatalog.forEach((entry) => {
    if (!providerLanguages.includes(entry.language)) {
      throw new Error(`Langue inconnue "${entry.language}" pour le provider ${entry.id}`);
    }
  });
}

export type ProviderCatalogEntry = (typeof providerCatalog)[number];

export const providerCatalogMap = providerCatalog.reduce<Record<string, ProviderCatalogEntry>>((acc, entry) => {
  acc[entry.id] = entry;
  return acc;
}, {});

export const getProviderMeta = (id: ProviderCatalogEntry["id"]): ProviderCatalogEntry => {
  const entry = providerCatalogMap[id];
  if (!entry) {
    throw new Error(`Provider ${id} introuvable dans le catalogue`);
  }
  return entry;
};
